import os
import shlex
import stat
import sys

from argparse import ArgumentParser

from pre_commit import main as pre_commit
from rh_pre_commit import config

RH_MULTI_PRE_COMMIT_HOOK = f"""#!/usr/bin/bash
# File generated by rh-multi-pre-commit
# ID: ed00ee75-4516-44ef-8b25-28ca3d18d91a

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mrh_pre_commit.multi
elif command -v rh-multi-pre-commit > /dev/null; then
    exec rh-multi-pre-commit
else
    echo '`rh-multi-pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""


def read_modfile(path):
    """
    Read the contents of a .git file and return the gitdir value if it exists
    """
    try:
        with open(os.path.join(path, ".git"), encoding="UTF-8") as modfile:
            for line in modfile:
                if line.startswith("gitdir: "):
                    return line.split(None, 1)[1].strip()

        return None
    except Exception:
        return None


def find_repos(prefix):
    """
    Find all git repos under a given prefix.

    Returns a collection of tuples:
        ("Repo Type", "Path")
    """
    target = f"{os.path.sep}.git"

    for path, _, files in os.walk(prefix):
        if path.endswith(target):
            yield ("R", path)

        elif ".git" in files:
            modpath = read_modfile(path)
            if modpath:
                yield ("M", os.path.join(path, modpath))


def create_parser():
    """
    Create an argparser to handle the arguments for the program
    """
    parser = ArgumentParser(
        prog="rh-multi-pre-commit",
        description="Manage multiple pre-commit hooks for Red Hatters",
    )

    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser(
        "update",
        help="Update the tool, "
        "force a patterns refresh, "
        "and update pre-commit hooks (global and current dir)",
    )

    install_parser = subparsers.add_parser(
        "install",
        help="Install the pre-commit hook in a project or projects",
    )
    install_parser.add_argument(
        "--check",
        action="store_true",
        help="Check to see where the hook would be installed, but don't install it",
    )
    install_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing pre-commit hooks"
    )
    install_parser.add_argument(
        "--path", default=".", required=False, help="The path to install the hooks in"
    )

    configure_parser = subparsers.add_parser(
        "configure",
        help="Reset the global rh-multi-pre-commit config",
    )
    configure_parser.add_argument(
        "--force", action="store_true", help="Do not prompt if existing config exists"
    )

    subparsers.add_parser(
        "login",
        help="Login to the pattern distribution server",
    )

    return parser


def list_repos(args):
    """
    A handler that lists all of the repos that would be impacted by the change
    """
    repos = sorted(find_repos(args.path), key=lambda r: r[1])

    for r_type, r_path in repos:
        print(r_type, r_path)

    return 0


def install_hook(args):
    """
    A handler that sets up a symlink for the pre-commit hook
    """

    for _, r_path in find_repos(args.path):
        hooks_dir = os.path.join(r_path, "hooks")
        hook_path = os.path.join(hooks_dir, "pre-commit")

        # Make sure the hooks dir exists
        if not os.path.exists(hooks_dir):
            try:
                os.mkdir(hooks_dir)
            except Exception:
                print(f"Could not create hooks dir: {hooks_dir}")
                continue

        if not args.force and os.path.exists(hook_path):
            print(f"{hook_path} already exists. Use --force to overwrite it.")
            continue

        try:
            with open(hook_path, "w", encoding="UTF-8") as hook_file:
                hook_file.write(RH_MULTI_PRE_COMMIT_HOOK)
        except Exception:
            print(f"Could not write {hook_path}")
            continue

        try:
            st = os.stat(hook_path)
            os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        except Exception:
            print(f"Could not make {hook_path} executable")


def run_pre_commit(_):
    """
    A handler that runs the pre_commit package
    """
    status = 0

    for path in config.RH_MULTI_CONFIG_PATHS:
        if not os.path.exists(path):
            continue

        status = pre_commit.main(
            (
                "run",
                f"--config={path}",
            )
        )

        if status:
            return status

    return status


def pick_handler(args):
    """
    Figure out how the args should be handled.

    A handler must take the args from the arg parser and return an exit code.
    """

    if args.command == "install":
        if args.check:
            return list_repos

        return install_hook

    return run_pre_commit


def main():
    try:
        args = create_parser().parse_args()
        handler = pick_handler(args)

        return handler(args)
    except KeyboardInterrupt:
        print("Exiting...")
        return 1


if __name__ == "__main__":
    sys.exit(main())
