#! /usr/bin/env bash
set -eou pipefail

export project_dir="$(cd ../../ && pwd)"
export base_repos="$(mktemp -d)"
export log_file="$(mktemp -d)/test.log"

function log {
  echo $@ | tee -a "${log_file}"
}

function test-case {
  log
  log "TEST:" $@
}

function pass {
  log "- ${1} (PASS)"
}

function fail {
  log "- ${1} (FAIL)"
  echo "====================================================================="
  echo "Log output"
  echo "---------------------------------------------------------------------"
  cat "${log_file}"
  echo "====================================================================="
  exit 1
}

function new-repo {
  cd $(mktemp -d)
  cp -r "${base_repos}/fake-leaks" ./fake-leaks
  cd ./fake-leaks
}

log "Running setup"

if [[ "$(id -u)" == "0" ]]
then
  curl -o /etc/pki/ca-trust/source/anchors/2015-RH-IT-Root-CA.pem \
    https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem >> "${log_file}" 2>&1

  curl -o /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem \
    https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem >> "${log_file}" 2>&1

  update-ca-trust >> "${log_file}" 2>&1
fi

# By using this repo we confirm the existing history isn't an issue
git clone https://github.com/leaktk/fake-leaks.git "${base_repos}/fake-leaks" >> "${log_file}" 2>&1
cd "${base_repos}/fake-leaks"

if ! git config user.email >> "${log_file}" 2>&1
then
  git config --global user.email "no-reply@redhat.com"
  git config --global user.name "No Reply"
fi

log "Installing hooks"
cd "${project_dir}" && make install >> "${log_file}" 2>&1

# Configure and install hooks
log "Configuring hooks"
cd "${base_repos}"
python3 -m "${HOOK}" --hook-type pre-commit configure --configure-git-template --force >> "${log_file}" 2>&1
python3 -m "${HOOK}" --hook-type commit-msg configure --configure-git-template --force >> "${log_file}" 2>&1
python3 -m "${HOOK}" --hook-type pre-commit install --force --path "${base_repos}" >> "${log_file}" 2>&1
python3 -m "${HOOK}" --hook-type commit-msg install --force --path "${base_repos}" >> "${log_file}" 2>&1

