#!/usr/bin/env bash
# File for use by ../.pre-commit-hooks.yaml
# ID: 9ffec9f6-9b91-4600-b96d-30ac691aa498
#
# NAME
#
#   rh-pre-commit-entry
#
# DESCRIPTION
#
#   This script provides an entry point for .pre-commit-hooks.yaml to use for
#   rh-pre-commit. The "python" language type won't work since this repo has
#   multiple projects in it.
#
#   This script should:
#
#   - Ensure there is a env with the versions of rh-pre-commit and rh-gitleaks
#     on this branch installed in it
#   - Exec /path/to/venv/bin/python -m rh_pre_commit and pass any cli args to it
#
# NOTES
#
#   - Once the rh-pre-commit code is open sourced, this script will probably
#     point at the open source packages and set Red Hat specific configuration
#     for backwards compatibility.
#
#   - This script currently does not auto-login rh-gitleaks, but rh-gitleaks
#     will provide a command to run to login if it fails. Also the auth token
#     from https://patterns.security.redhat.com can be set via the
#     LEAKTK_PATTERN_SERVER_AUTH_TOKEN env var.
#
set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
VENV_DIR="${SCRIPTS_DIR}/../venv"

# Lazy set up and run the venv python
function venv_python {
  # Ensure the cache dir exists
  if [[ ! -d "${VENV_DIR}" ]]
  then
    python3 -m venv "${VENV_DIR}"
  fi

  "${VENV_DIR}/bin/python3" $@
}

# Make sure the version of the package in the venv matches whats in this
# branch of the repo
function sync_version {
  project="${1}"
  expected="$("${SCRIPTS_DIR}/tool-version" "${project}")"
  actual="$(venv_python -m pip list 2> /dev/null | grep "^${project}\s" | awk '{print $2}' || echo "")"

  if [[ "${actual}" != "${expected}" ]]
  then
    if [[ ! -z "${actual}" ]]
    then
      # Start fresh if an older version exists
      rm --preserve-root -rf "${VENV_DIR}"
    fi

    venv_python -m pip install "${SCRIPTS_DIR}/../${project}"
  fi
}

sync_version rh-gitleaks
sync_version rh-pre-commit
venv_python -m rh_pre_commit $@
