#!/usr/bin/env python3
#
# File for getting versions of tools in this repo
# ID: 8e7309c7-7253-4328-b90d-e212a95f26e9
#
# USAGE
#
#   tool-version <tool-name>
#
# DESCRIPTION
#
#   This is not meant to be used by individuals directly. Only by other scripts
#   in this repo.
#
import sys
import re

from pathlib import Path


def main():
    project_dir = Path(__file__).parent.resolve() / ".." / sys.argv[1]
    pyproject_path = project_dir / "pyproject.toml"
    block_re = re.compile(r"\s*\[")
    project_re = re.compile(r"\s*\[project\]")
    version_re = re.compile(r"\s*version\s*=\s*[\"\']([^\"\']+?)[\"\']")
    in_project_block = False

    with open(pyproject_path, "r", encoding="UTF-8") as pyproject_file:
        for line in pyproject_file:
            if in_project_block:
                if block_re.match(line):
                    # Went through the block and didn't find it
                    return 1

                version_match = version_re.match(line)
                if version_match:
                    print(version_match.group(1))
                    return 0
            else:
                in_project_block = bool(project_re.match(line))

    return 1


if __name__ == "__main__":
    sys.exit(main())
