#! /usr/bin/env python3

"""
Created: 2022-12
Author: Braxton Plaxco
Description:

    This script is meant to uninstall the bash versions of rh-gitleaks,
    rh-pre-commit, and related scripts.

    It will make changes to your system, but it will describe the changes
    and ask for confirmation before doing so.

    The script may prompt you for a sudo password if the tools were installed
    globally.

Notes:

    This will only remove the scripts if they are on your current $PATH
"""

import os
import sys

potential_legacy_scripts = {
    "rh-gitleaks",
    "rh-gitleaks-gh-account",
    "rh-multi-pre-commit",
    "rh-pre-commit",
}


def is_legacy_script(script_path):
    with open(script_path, "rb") as script_file:
        return b"/bin/bash" in script_file.read()


def locate_legacy_scripts():
    for exec_path in os.environ["PATH"].split(":"):
        for path, _, files in os.walk(exec_path):
            for file in files:
                if file not in potential_legacy_scripts:
                    continue

                script_path = os.path.join(path, file)
                if is_legacy_script(script_path):
                    yield script_path


def sudo_required(path):
    return not os.access(os.path.dirname(path), os.W_OK | os.X_OK)


def uninstall_command(path):
    become = "sudo" if sudo_required(path) else ""
    return f"{become} rm -f {path}".strip()


def main():
    legacy_scripts = list(locate_legacy_scripts())

    if not legacy_scripts:
        print("No legacy scripts were found!")
        return 0

    commands = []
    print("This script will run the following commands: \n")
    for script_path in legacy_scripts:
        command = uninstall_command(script_path)
        commands.append(command)
        print(command)

    resp = input("\nContinue? [y/n]: ").lower().strip()
    if resp != "y":
        print("Aborting...")
        return 1

    status = 0
    for command in commands:
        print("Running", command)
        if os.system(command) != 0:
            status = 1

    return status


if __name__ == "__main__":
    sys.exit(main())
