PREFIX := /usr/local

install:
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	install ./bin/rh-gitleaks $(DESTDIR)$(PREFIX)/bin/rh-gitleaks
	install ./bin/rh-gitleaks-gh-account $(DESTDIR)$(PREFIX)/bin/rh-gitleaks-gh-account
