#! /usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

image="${1}"

podman run  \
  -u root --rm -i \
  --security-opt=label=disable \
  --volume="${SCRIPT_DIR}/../../..:/source:ro" \
  --env="LEAKTK_PATTERN_SERVER_AUTH_TOKEN=$(cat ${HOME}/.config/rh-gitleaks/auth.jwt)" \
  --workdir="/source/rh-pre-commit/tests/integration" \
  "${image}" ./${@:2}
