#! /usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
GITREF="$(git rev-parse --abbrev-ref HEAD)"

function run-test {
  cd "${SCRIPT_DIR}"

  if which podman &> /dev/null
  then
    echo "====================================================================="
    echo "Running in RHEL"
    echo "---------------------------------------------------------------------"
    ./run-in-rhel test-hook ${@} container
    echo "====================================================================="
    echo
    echo "====================================================================="
    echo "Running in Fedora"
    echo "---------------------------------------------------------------------"
    ./run-in-fedora test-hook ${@} container
    echo "====================================================================="
  else
    echo "====================================================================="
    echo "Podman not found. Skipping Linux tests"
    echo "====================================================================="
  fi

  echo
  echo "====================================================================="
  echo "Running on host (WARNING this resets host config)"
  echo "---------------------------------------------------------------------"
  ./test-hook ${@} host
  echo "====================================================================="
}

run-test rh_pre_commit "${GITREF}"
run-test rh_pre_commit.multi "${GITREF}"
