#! /usr/bin/bash

HOOK="${1}"
source ./common/setup

echo "Testing Hook: ${HOOK}"

cd "${test_repos}/repo-1"
echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
git add secret

# Confirm it is caught

if ! git commit -m "This should fail"
then
  echo "${HOOK} detected secrets"
else
  echo "${HOOK} did not detect secrets"
  exit 1
fi

# This should allow the commit

cat > .gitleaks.toml << EOF
[allowlist]
paths = [
  'secret'
]
EOF
git add .gitleaks.toml

if git commit -m "This should pass"
then
  echo "${HOOK} allowlist works"
else
  echo "${HOOK} allowlist did not work"
  exit 1
fi

# Confirm the check can just be disabled

cd "${test_repos}/repo-2"
echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
git add secret

if ! git commit -m "This should fail"
then
  echo "${HOOK} detected secrets"
else
  echo "${HOOK} did not detect secrets"
  exit 1
fi

git config --bool rh-pre-commit.checkSecrets false

if git commit -m "This should pass"
then
  echo "${HOOK} git config works"
else
  echo "${HOOK} git config did not work"
  exit 1
fi
