#! /usr/bin/env bash
#
# WARNING: these tests are run on the host too. Try to make sure that
# they aren't destructive and work outside of a container
#
#
# General test case format:
#
# -----------------------------------------------------------------------------
#
# test-case "Confirm ...."
#
# <set-up commands>
#
# tests with pass/fail messages called to show the results
#
# <tear-down commands>
#
# -----------------------------------------------------------------------------
#
# And new-repo can be called to create a fresh copy of the repo. The extra
# comments around it are to help make this more obvious
#
# If fail is called, the contents of ${log_file} are displayed. Both pass and
# fail also log to the log_file
#
set -euo pipefail

HOOK="${1}"
GITREF="${2}"
ENVTYPE="${3}"

source ./common/setup

log
log "Testing Hook: ${HOOK}"

# New Repo ####################################################################
new-repo
###############################################################################

if [[ "${HOOK}" = "rh_pre_commit.multi" ]]
then
  test-case "Confirm local config disabled by default for multi installs"

  if grep "enableLocalConfig\s*=\s*false" ~/.gitconfig >> "${log_file}" 2>&1
  then
    pass "local config disabled by default"
  else
    fail "local config not disabled by default"
  fi
else
  if [[ "${ENVTYPE}" == "container" ]]
  then
    test-case "Confirm local config setting not set for normal installs"

    if grep "enableLocalConfig" ~/.gitconfig >> "${log_file}" 2>&1
    then
      fail "enableLocalConfig should not be set for ${HOOK}"
    else
      pass "enableLocalConfig not set for ${HOOK}"
    fi
  fi
fi

# -----------------------------------------------------------------------------

test-case "Confirm the pre-commit hook template is installed"

if grep "${HOOK}" ~/.git-template/hooks/pre-commit >> "${log_file}" 2>&1
then
  pass "${HOOK} type:pre-commit installed"
else
  fail "${HOOK} type:pre-commit not installed"
fi

# -----------------------------------------------------------------------------

test-case "Confirm the commit-msg hook template is installed"

if grep "${HOOK}" ~/.git-template/hooks/commit-msg >> "${log_file}" 2>&1
then
  pass "${HOOK} template type:commit-msg installed"
else
  fail "${HOOK} template type:commit-msg not installed"
fi

# -----------------------------------------------------------------------------

test-case "Confirm it doesn't block on secrets that are not staged during a commit"

echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret

if git commit --allow-empty -m "This should pass" >> "${log_file}" 2>&1
then
  pass "${HOOK} unstaged secret not blocked"
else
  fail "${HOOK} unstaged secret blocked"
fi

# -----------------------------------------------------------------------------

test-case "Confirm staged secrets are caught"

git add secret

if ! git commit -m "This should error" >> "${log_file}" 2>&1
then
  pass "${HOOK} detected secrets"
else
  fail "${HOOK} did not detect secrets"
fi

# -----------------------------------------------------------------------------

test-case "Confirm a notsecret allows a secret"

echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g" #notsecret' > secret
git add secret

if git commit -m "This should pass" >> "${log_file}" 2>&1
then
  pass "${HOOK} notsecret comment works"
else
  fail "${HOOK} notsecret comment did not work"
fi

# -----------------------------------------------------------------------------

test-case "Confirm a .gitleaks.toml should allow secrtes"

echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
git add secret

cat > .gitleaks.toml << EOF
[allowlist]
paths = [
  'secret'
]
EOF
git add .gitleaks.toml

if git commit -m "This should pass" >> "${log_file}" 2>&1
then
  pass "${HOOK} allowlist works"
else
  fail "${HOOK} allowlist did not work"
fi

# -----------------------------------------------------------------------------

test-case "Confirm it signed off on the commits as ENABLED"

if git log -n 1 | grep "rh-pre-commit.check-secrets: ENABLED" >> "${log_file}" 2>&1
then
  pass "It was detected as enabled"
else
  fail "It was not detected as enabled"
fi

# New Repo ####################################################################
new-repo
###############################################################################

test-case "Confirm the task can just be disabled"

echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
git add secret

if ! git commit -m "This should error" >> "${log_file}" 2>&1
then
  pass "${HOOK} detected secrets when the task is enabled"
else
  fail "${HOOK} did not detect secrets when the task was enabled"
fi

git config --bool rh-pre-commit.checkSecrets false

if git commit -m "This should pass" >> "${log_file}" 2>&1
then
  pass "${HOOK} secrets commited when task disabled"
else
  fail "${HOOK} secrets could not be commited when the task was disabled"
fi

# -----------------------------------------------------------------------------

test-case "Confirm sign-off knows when hooks are disabled"

git config --bool rh-pre-commit.checkSecrets false
git commit --allow-empty -m "some commit" >> "${log_file}" 2>&1

if git log -n 1 | grep "rh-pre-commit.check-secrets: DISABLED" >> "${log_file}" 2>&1
then
  pass "It was detected as disabled"
else
  fail "It was not detected as disabled"
fi

# New Repo ####################################################################
new-repo
###############################################################################

test-case "Confirm the local hook setting is respected"

cat > .pre-commit-config.yaml <<EOF
repos:
  - repo: local
    hooks:
      - id: failing-hook
        name: Failing Hook
        language: system
        entry: false
        stages: [pre-commit]
        pass_filenames: false
EOF
git add .pre-commit-config.yaml

if git commit -m "This should pass" >> "${log_file}" 2>&1
then
  pass ".pre-commit-config.yaml local config ignored"
else
  fail ".pre-commit-config.yaml local config not ignored"
fi

# -----------------------------------------------------------------------------

if [[ "${HOOK}" == "rh_pre_commit.multi" ]]
then
  test-case "Confirm the local config can be enabled for ${HOOK}"

  git config --bool rh-pre-commit.enableLocalConfig true
  touch some-file && git add some-file # Force a change for a commit

  if git commit -m "This should error" >> "${log_file}" 2>&1
  then
    fail ".pre-commit-config.yaml local config not applied"
  else
    pass ".pre-commit-config.yaml local config applied"
  fi
else
  test-case "Confirm the local config cannot be enabled for ${HOOK}"

  git config --bool rh-pre-commit.enableLocalConfig true
  touch some-file && git add some-file # Force a change for a commit

  if git commit -m "This should pass" >> "${log_file}" 2>&1
  then
    pass ".pre-commit-config.yaml local config ignored"
  else
    fail ".pre-commit-config.yaml local config not ignored"
  fi
fi

# New Repo ####################################################################
new-repo
###############################################################################

test-case "Confirm it's not enabled for this repo yet and sign-off blocks it"
# This is because we have the commit-msg installed but not the pre-commit
# hook in any way

python3 -m pre_commit install --hook-type pre-commit -f >> "${log_file}" 2>&1
echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret-not-caught
cat > .pre-commit-config.yaml <<EOF
repos: []
EOF
git add .pre-commit-config.yaml secret-not-caught

if grep "${HOOK}" .git/hooks/pre-commit >> "${log_file}" 2>&1
then
  fail "${HOOK} not pre-commit hook replaced"
else
  pass "${HOOK} pre-commit hook replaced"
fi

if git commit -m "Sign-off should stop the commit" >> "${log_file}" 2>&1
then
  fail "Sign-off did not catch the commit"
else
  pass "Sign-off caused the commit to fail because rh-pre-commit wasn't installed"
fi

# -----------------------------------------------------------------------------

test-case "Confirm pre-commit not enabled for this repo yet and sign-off has been turned off"
# With both pre-commit and commit-msg off we should be able to commit secrets
# to the repo now

git config --bool rh-pre-commit.commit-msg.signOff false

if git commit -m "This should pass" >> "${log_file}" 2>&1
then
  pass "Secret not caught yet"
else
  fail "Secret detected when it shouldn't be"
fi

if git log -n 1 | grep "rh-pre-commit" >> "${log_file}" 2>&1
then
  fail "Sign-off was still enabled"
else
  pass "Sign-off was disabled properly"
fi

# -----------------------------------------------------------------------------

test-case "Confirm both pre-commit and commit-msg can be installed through its .pre-commit-hooks.yaml"

git config --bool rh-pre-commit.commit-msg.signOff true
python3 -m pre_commit install --hook-type commit-msg -f >> "${log_file}" 2>&1
cat > .pre-commit-config.yaml <<EOF
repos:
  - repo: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools.git
    rev: ${GITREF}
    hooks:
      - id: rh-pre-commit
      - id: rh-pre-commit.commit-msg
EOF
mv secret-not-caught secret
git add .pre-commit-config.yaml secret

if grep "${HOOK}" .git/hooks/pre-commit >> "${log_file}" 2>&1
then
  fail "${HOOK} not pre-commit hook replaced"
else
  pass "${HOOK} pre-commit hook replaced"
fi

if grep "${HOOK}" .git/hooks/commig-msg >> "${log_file}" 2>&1
then
  fail "${HOOK} commit-msg hook not replaced"
else
  pass "${HOOK} commmit-msg hook replaced"
fi

if git commit -m "This should error" >> "${log_file}" 2>&1
then
  fail "Secret not caught"
else
  pass "Secret caught"
fi

# -----------------------------------------------------------------------------

test-case "Confirm it doesn't block on secrets that are not staged during a commit"

git commit --no-verify -m "Commit staged to get it out of the way" >> "${log_file}" 2>&1
echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > unstaged

if git commit --allow-empty -m "This should pass" >> "${log_file}" 2>&1
then
  pass "Unstaged secret not blocked"
else
  fail "Unstaged secret blocked"
fi

rm unstaged

# -----------------------------------------------------------------------------

test-case "Confirm it signed off on the commits as ENABLED (i.e. it detected it from the .pre-commit-config.yaml in the repo)"

if git log -n 1 | grep "rh-pre-commit.check-secrets: ENABLED" >> "${log_file}" 2>&1
then
  pass "It was detected as enabled"
else
  fail "It was not detected as enabled"
fi

# -----------------------------------------------------------------------------

if [[ "${ENVTYPE}" == "container" ]]
then

  test-case "Confirm it doesn't fail if the cached patterns exist but the creds don't"

  SAVED_TOKEN="${LEAKTK_PATTERN_SERVER_AUTH_TOKEN}"
  unset LEAKTK_PATTERN_SERVER_AUTH_TOKEN
  echo 'Hello, world!' > some-file
  git add some-file

  if git commit -m "This should pass" >> "${log_file}" 2>&1
  then
    pass "rh-gitleaks ran without an issue"
  else
    fail "rh-gitleaks ran with issues"
  fi

  export LEAKTK_PATTERN_SERVER_AUTH_TOKEN="${SAVED_TOKEN}"
  unset SAVED_TOKEN

  # ---------------------------------------------------------------------------

  test-case "Confirm it shows a helpful login message when it can't contact the pattern server"

  SAVED_TOKEN="${LEAKTK_PATTERN_SERVER_AUTH_TOKEN}"
  unset LEAKTK_PATTERN_SERVER_AUTH_TOKEN
  rm -rf ~/.cache/rh-gitleaks
  echo 'Hello (again), world!' > some-other-file
  git add some-other-file

  commit_output="$(git commit -m "This should error" 2>&1 || true)"

  if echo "${commit_output}" | grep 'Could not find pattern server auth token' >> "${log_file}" 2>&1
  then
    pass "A failure reason was provided"
  else
    fail "A failure reason not was provided"
  fi

  if echo "${commit_output}" | grep 'Please log in with this command and try again' >> "${log_file}" 2>&1
  then
    pass "Login instructions were provided"
  else
    fail "Login instructions were not provided"
  fi

  if echo "${commit_output}" | grep '/python3 -m rh_gitleaks login' >> "${log_file}" 2>&1
  then
    pass "A login example was provided"
  else
    fail "A login example was not provided"
  fi

  git rm -f some-other-file >> "${log_file}" 2>&1
  export LEAKTK_PATTERN_SERVER_AUTH_TOKEN="${SAVED_TOKEN}"
  unset SAVED_TOKEN
fi

# New Repo ####################################################################
new-repo
###############################################################################

test-case "Confirm ammends don't double add the sign-off"

touch some-file
git add some-file
git commit -m "Add some file" >> "${log_file}" 2>&1
enabled_str="rh-pre-commit.check-secrets: ENABLED"

if git log -n 1 | grep "${enabled_str}" >> "${log_file}" 2>&1
then
  pass "The inital sign-off is there"
else
  fail "The inital sign-off not is there"
fi

git commit --amend -m "Add some file" >> "${log_file}" 2>&1

enabled_count="$(git log -n 1 | grep "${enabled_str}" | sort | uniq -c | awk '{print $1}')"

if [[ "${enabled_count}" = "1" ]]
then
  pass "The sign-off only shows once"
else
  fail "The sign-off shows more than once"
fi

# -----------------------------------------------------------------------------
