#! /bin/bash
set -euo pipefail

if [[ "$1" == "--check" ]]
then
  shift
  action="echo"
else
  action="enable-hook"
fi

prefix="$1"
hook="$(which rh-multi-pre-commit)"

function enable-hook {
  echo "Enabling in $1"
  mkdir -p "$1/hooks" && ln -snf "${hook}" "$1/hooks/pre-commit" || true
}

function find-repos {
  find "${prefix}" -name .git -type d 2> /dev/null
}

function find-modules {
  find "${prefix}" -name .git -type f 2> /dev/null \
    | xargs dirname \
    | xargs -I '{}' bash -c "echo \"{}/\$(grep 'gitdir:' {}/.git | awk '{print \$2}')\""
}

for repo in $(find-repos) $(find-modules)
do
  "${action}" "${repo}"
done
