#! /bin/sh
set -ex

export USE_VENV=false
source ./scripts/common

cd ../rh-gitleaks && make install

if [ "$VENV_ROOT" != "" ] || [ $(id -u) -eq "0" ]; then
  INSTALL_FLAGS=""
else
  INSTALL_FLAGS="--user"
fi

$PYTHON setup.py install $INSTALL_FLAGS
