#! /bin/sh
set -ex

package="rh-pre-commit"
version="$(../scripts/tool-version "${package}")"
rpm_dir="$(pwd)/rpmbuild"
srpm_dir="${rpm_dir}/SRPMS"

mkdir -p $srpm_dir

rpkg srpm --outdir $srpm_dir
rpmbuild -rb \
  --define "_topdir %(pwd)/rpmbuild" \
  "${srpm_dir}/${package}-${version}-1.src.rpm"
