#! /bin/sh
set -ex

find . -type f -regex ".*\.py[co]$" -delete
find . -type f \( -name "*~" \) -delete
find . -type f \( -name "#*" \) -delete
find . -type f \( -name "*.log" \) -delete
find . -type d \( -name "__pycache__" \) -delete
find . -type d \( -name "*.egg-info" \) -prune -exec rm -rf '{}' '+'

rm -rf .coverage .pytest_cache htmlcov dist build rpmbuild wheelhouse dependency-check-report.html
