#! /bin/sh
set -ex

export USE_VENV=false
source ./scripts/common

if [ "$VENV_ROOT" != "" ] || [ $(id -u) -eq "0" ]; then
  INSTALL_FLAGS=""
else
  INSTALL_FLAGS="--user"
fi

$PIP_INSTALL $INSTALL_FLAGS .
