#! /bin/sh
set -ex

source ./scripts/common
PROJECT_DIR=$(pwd)

$PIP_WHEEL . -w ./wheelhouse
for req_file in $(find . -name requirements.txt); do
  $PIP_WHEEL -r $req_file -w ./wheelhouse
done

rm -rf /tmp/dependency-check
mkdir -p /tmp/dependency-check

cd /tmp/dependency-check

curl -O $(curl https://nexus.corp.redhat.com/repository/infosec-raw/dependency-check/releases/any/latest-url)
curl -O https://nexus.corp.redhat.com/repository/infosec-raw/dependency-check/releases/any/latest-checksum
sha256sum --check latest-checksum

unzip dependency-check-*-release.zip && rm dependency-check-*-release.zip
cd $PROJECT_DIR

/tmp/dependency-check/dependency-check/bin/dependency-check.sh --enableExperimental --project $(basename $PROJECT_DIR) --scan $PROJECT_DIR/wheelhouse || true
rm -rf /tmp/dependency-check $PROJECT_DIR/wheelhouse
$OPEN_FILE dependency-check-report.html
