import sys
import shlex

import rh_gitleaks.config

# If making any significant changes to this template, change the ID so
# that it is easier to locate older versions
RH_MULTI_PRE_COMMIT_HOOK = {
    "pre-commit": f"""#!/usr/bin/env bash
# File generated by rh-multi-pre-commit
# ID: 308ef274-3374-479a-b03a-298d8fdbba34

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit.multi
elif command -v rh-multi-pre-commit > /dev/null; then
    exec rh-multi-pre-commit
else
    echo '`rh-multi-pre-commit` not found.' 1>&2
    echo 'For more information: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit' 1>&2
    exit 1
fi
""",
    "commit-msg": f"""#!/usr/bin/env bash
# File generated by rh-multi-pre-commit
# ID: 7ad444b3-4a97-482b-bd5f-9d290eb17663

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit.multi  --hook-type commit-msg --commit-msg-filename $1
elif command -v rh-multi-pre-commit > /dev/null; then
    exec rh-multi-pre-commit --hook-type commit-msg --commit-msg-filename $1
else
    echo '`rh-multi-pre-commit` not found.' 1>&2
    echo 'For more information: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit' 1>&2
    exit 1
fi
""",
}

RH_PRE_COMMIT_HOOK = {
    "pre-commit": f"""#!/usr/bin/env bash
# File generated by rh-pre-commit
# ID: 13f5c8db-62a3-4ca8-ad21-2f27d83f8068

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit
elif command -v rh-pre-commit > /dev/null; then
    exec rh-pre-commit
else
    echo '`rh-pre-commit` not found.' 1>&2
    echo 'For more information: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit' 1>&2
    exit 1
fi
""",
    "commit-msg": f"""#!/usr/bin/env bash
# File generated by rh-pre-commit
# ID: 7f4bf7f0-e2f5-4c86-af41-949a29fb5ef5

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit --hook-type commit-msg --commit-msg-filename $1
elif command -v rh-pre-commit > /dev/null; then
    exec rh-pre-commit --hook-type commit-msg --commit-msg-filename $1
else
    echo '`rh-pre-commit` not found.' 1>&2
    echo 'For more information: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit' 1>&2
    exit 1
fi
""",
}

RH_MULTI_CONIFG = f"""\
repos:
  - repo: local
    hooks:
      - id: rh-pre-commit
        name: Run standard RH pre-commit checks
        language: system
        entry: {shlex.quote(sys.executable)} -m rh_pre_commit
        stages: [ pre-commit ]
        pass_filenames: false
      - id: rh-pre-commit-msg
        name: Append attestation to commit-msg
        language: system
        entry: {shlex.quote(sys.executable)} -m rh_pre_commit --hook-type commit-msg --commit-msg-filename 
        stages: [ commit-msg ]
        pass_filenames: true
"""

LEAK_DETECTED = f"""\
ERROR: rh-gitleaks has detected sensitive information in your changes and will
not allow the commit to proceed.

If it the file contains sensitive information, please remove it and try
your commit again.

If the detection was a false positive, the documentation[1] contains a section
for handling false positives.

[1] {rh_gitleaks.config.PATTERN_SERVER_DOCS_URL}
"""
