import sys
import shlex

# If making any significant changes to this template, change the ID so
# that it is easier to locate older versions
RH_MULTI_PRE_COMMIT_HOOK = f"""#!/usr/bin/bash
# File generated by rh-multi-pre-commit
# ID: ed00ee75-4516-44ef-8b25-28ca3d18d91a

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mrh_pre_commit.multi
elif command -v rh-multi-pre-commit > /dev/null; then
    exec rh-multi-pre-commit
else
    echo '`rh-multi-pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""

# TODO: See if this can be pointed directly at the repo. If not change
# it so that it doesn't rely on rh-pre-commit being on your path. See
# RH_MULTI_PRE_COMMIT_HOOK above
RH_MULTI_CONIFG = """
repos:
  - repo: local
    hooks:
      - id: rh-pre-commit
        name: Run standard RH pre-commit checks
        language: system
        entry: rh-pre-commit
"""
