import sys
import shlex

import rh_gitleaks.config

# If making any significant changes to this template, change the ID so
# that it is easier to locate older versions
RH_MULTI_PRE_COMMIT_HOOK = f"""#!/usr/bin/bash
# File generated by rh-multi-pre-commit
# ID: ed00ee75-4516-44ef-8b25-28ca3d18d91a

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit.multi
elif command -v rh-multi-pre-commit > /dev/null; then
    exec rh-multi-pre-commit
else
    echo '`rh-multi-pre-commit` not found.' 1>&2
    echo 'For more information: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools/-/blob/main/rh-pre-commit/README.md' 1>&2
    exit 1
fi
"""

RH_PRE_COMMIT_HOOK = f"""#!/usr/bin/bash
# File generated by rh-pre-commit
# ID: 378a113b-5011-4170-9dd7-9ee9e37366b3

INSTALL_PYTHON={shlex.quote(sys.executable)}

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m rh_pre_commit
elif command -v rh-pre-commit > /dev/null; then
    exec rh-multi-pre-commit
else
    echo '`rh-pre-commit` not found.' 1>&2
    echo 'For more information: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools/-/blob/main/rh-pre-commit/README.md' 1>&2
    exit 1
fi
"""

RH_MULTI_CONIFG = f"""\
repos:
  - repo: local
    hooks:
      - id: rh-pre-commit
        name: Run standard RH pre-commit checks
        language: system
        entry: {shlex.quote(sys.executable)} -m rh_pre_commit
        pass_filenames: false
"""

LEAK_DETECTED = f"""\
ERROR: rh-gitleaks has detected sensitive information in your changes and will
not allow the commit to proceed.

If it the file does contain sensitive information, please remove it and try
your commit again.

If the detection was a false positive you can either add a gitleaks:allow
comment to the line to allow it or add a .gitleaks.toml in your repo's base
directory with the item added to the allow list.

For example, if the the pattern 'redhat.com' and file
'some/file/here.txt' are causing the problem, your .gitleaks.toml will
look like:

    [allowlist]
    description = "Global Allowlist"

    # (Optional) If you want to allow by file path
    paths = [
        '''some\\/file\\/here\\.txt''',
    ]

    # (Optional) If you want to allow by regex
    regexes = [
        '''redhat\\.com''',
    ]

If you have any questions, issues, or want to report a potential data
leak, further instructions can be found in these docs:

{rh_gitleaks.config.PATTERNS_SERVER_DOCS_URL}
"""
